#!/bin/bash
set -eu

rm -rf config
cp -a config.in config

MIRROR=${MIRROR:-http://archive.ubuntu.com/ubuntu}
COMPONENTS='main restricted universe multiverse'
SUITE=`lsb_release -cs`

lb config noauto \
        --mode ubuntu \
        --distribution $SUITE \
	--architectures $ARCH \
        --bootstrap-keyring ubuntu-keyring \
        --binary-images iso-hybrid \
        --memtest memtest86+ \
        --source false \
        --build-with-chroot false \
        --parent-mirror-bootstrap $MIRROR \
        --parent-mirror-chroot-security $MIRROR \
        --parent-mirror-chroot-backports $MIRROR \
        --parent-mirror-chroot-volatile $MIRROR \
        --mirror-bootstrap $MIRROR \
        --mirror-chroot-security $MIRROR \
        --mirror-chroot-backports $MIRROR \
        --mirror-chroot-volatile $MIRROR \
        --parent-mirror-binary $MIRROR \
        --parent-mirror-binary-security $MIRROR \
        --parent-mirror-binary-backports $MIRROR \
        --archive-areas "main restricted universe" \
        --tasksel tasksel \
        --package-lists none \
        --initsystem none \
        --bootloader syslinux \
        --initramfs-compression lzma \
        --apt-http-proxy http://127.0.0.1:3142/

cat > config/binary_rootfs/excludes << EOF
boot/vmlinu?-*
boot/initrd.img-*
EOF

ln -s /usr/share/live/build/examples/hooks/all_chroot_pyc-purge.sh config/chroot_local-hooks/
ln -s /usr/share/live/build/examples/hooks/kubuntu_chroot_icon-theme.sh config/chroot_local-hooks/

. config/bootstrap
cat > config/archives/dvd.binary.list << EOF
deb $LB_PARENT_MIRROR_BINARY $SUITE universe multiverse
deb $LB_PARENT_MIRROR_BINARY_SECURITY $SUITE-security universe multiverse
deb $LB_PARENT_MIRROR_BINARY_VOLATILE $SUITE-updates universe multiverse
EOF
