#!/bin/sh
export LANG=C
export SUITE=$(lsb_release -cs)

if [ "$(id -u)" = 0 ]; then
	SUDO=env
else
	SUDO=sudo
fi

# Make sure all our dependencies (which are Recommends of our package) are
# installed.  This is a bit dubious long-term, but seems to be needed to
# make autobuilds reliable.
$SUDO apt-get -y install syslinux-themes-ubuntu gfxboot-theme-ubuntu memtest86+ syslinux
$SUDO apt-get -y install genisoimage

$SUDO lb clean
rm -f .stage/config

lb config

sed -i "s/^\\(LB_SYSLINUX_THEME=\\).*/\\1\"squibby-$SUITE\"/" config/binary

# work around live-build failure with lzma initramfs (Debian #637979)
sed -i 's/^LB_INITRAMFS_COMPRESSION="lzma"/LB_INITRAMFS_COMPRESSION="gzip"/' config/common

$SUDO lb build
