#!/bin/sh
set -e

ARCH=$(dpkg --print-architecture)

mkdir germinate-out packages

cd germinate-out
germinate -S http://bazaar.launchpad.net/~squibbylinux/squibbylinux/ \
          -s squibby-desktop.precise \
          -m http://localhost:3142/ubuntu/ \
          -m http://ppa.lauchpad.net/squibbylinux/stable/ubuntu \
          -d precise,precise-updates,precise-security \
          -a ${ARCH} \
          -c main,restricted,universe \
          --bzr

cd ../packages
for i in live desktop desktop-common standard minimal required boot ship-live ship-live.build-depends; do
    < ../germinate-out/$i \
    tail -n +3 | head -n -2 | cut -d' ' -f1 > $i.packages
done

cat > extra.packages << EOF
tasksel
tasksel-data
squibby-tasks
EOF

cat live.packages \
    desktop.packages \
    desktop-common.packages \
    standard.packages \
    minimal.packages \
    required.packages \
    extra.packages | sort -u \
    > ../config.in/package-lists/livecd-rootfs.chroot.list

cat ship-live.packages \
    ship-live.build-depends.packages \
    > ../config.in/package-lists/ship-live.binary.list

cd ..
echo "Updating complete!"

rm -rf germinate-out packages
