#!/bin/bash
set -e

ARCH=$(dpkg --print-architecture)

for i in seeds germinate-out packages; do
	if [[ -d "$i" ]]; then
		rm -rf "$i"
	fi
	mkdir $i
done

SEEDS=`pwd`/seeds
cd seeds
bzr branch http://bazaar.launchpad.net/~squibbylinux/squibbylinux/squibby-desktop.precise
bzr branch http://bazaar.launchpad.net/~ubuntu-core-dev/ubuntu-seeds/platform.precise

cd ../germinate-out
germinate -S file://$SEEDS \
          -s squibby-desktop.precise \
          -m http://localhost:3142/ubuntu/ \
          -m http://ppa.lauchpad.net/squibbylinux/stable/ubuntu \
          -d precise,precise-updates,precise-security \
          -a ${ARCH} \
          -c main,restricted,universe

cd ../packages
for i in ship-live ship-live.build-depends; do
    < ../germinate-out/$i \
    tail -n +3 | head -n -2 | cut -d' ' -f1 > $i.packages
done

cat ship-live.packages \
    ship-live.build-depends.packages | sort -u \
    > ../config.in/package-lists/ship-live.binary.list

cd ..
rm -rf seeds germinate-out packages

echo "Updating complete!"
